##
# (c) 2022 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
release:
- any: [ 'terraform.tfvars' ]

config:
- any: [ 'values/**/*' ]

owners:
- any: [ 'OWNERS' ]

size-XS:
- any: [ 'README.*' ]

size-L:
- any: [ '**/*.tf', '!*.tfvars', '!*-module.tf' ]