##
# (c) 2021 - Cloud Ops Works LLC - https://cloudops.works/
#            On GitHub: https://github.com/cloudopsworks
#            Distributed Under Apache v2.0 License
#
name: Environment Promotion
on:
  repository_dispatch:
    types:
      - promote-environment
      - promote-env

permissions:
  issues: write
  checks: read
  deployments: write
  contents: write
  packages: read
  statuses: write

jobs:
  env-promotion:
    concurrency:
      group: deploy-promotion
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Output payload
        run: |
          echo "This is the payload received"
          echo "${{ github.event.client_payload }}"

      # Checkout this repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.BOT_TOKEN }}

      # Installs Terraform
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Create version File
        run: |
          echo "VERSION=${{ github.event.client_payload.promote.version }}" > VERSION
          echo "CHART=${{ github.event.client_payload.promote.repository }}" >> VERSION
          echo "TARGET=${{ github.event.client_payload.promote.releasename }}" >> VERSION
          echo "PLATFORM=${{ github.event.client_payload.promote.platform }}" >> VERSION

      - name: Push change for release
        run: |
          make version

      # Do Tidy on terraform Files
      - name: Terraform tidy up
        run: terraform fmt

      - name: Push change to Branch
        id: push
        run: |
          git add .
          git config --global user.name "${{ secrets.BOT_USER }}"
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          MSG="chore: promote from ${{ github.event.client_payload.promote.repository }} to ${{ github.event.client_payload.promote.releasename }} - v${{ github.event.client_payload.promote.version }}"
          tracking=${{ github.event.client_payload.promote.trackingid }}
          if [ "a$tracking" != "a" ] ; then
            MSG="$MSG - Fixes: $tracking"
            echo "trackingid=TrackingID/$tracking" >> $GITHUB_OUTPUT
          fi
          echo "message=$MSG" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "${{ steps.push.outputs.message }}"
          committer: ${{ secrets.BOT_USER }} <${{ secrets.BOT_EMAIL }}>
          branch: promote-${{ github.event.client_payload.promote.releasename }}-v${{ github.event.client_payload.promote.version }}
          #base: "master"
          title: "Promote ${{ github.event.client_payload.promote.releasename }} v${{ github.event.client_payload.promote.version }}"
          token: ${{ secrets.BOT_TOKEN }}
          labels: ${{ steps.push.outputs.trackingid }}
          body: |
            Promotion of ${{ github.event.client_payload.promote.releasename }} v${{ github.event.client_payload.promote.version }}
            Automatic Merge will be performed upon approval

            Closes ${{ github.event.client_payload.promote.fromissue }} by ${{ github.event.client_payload.promote.fromauthor }}
